version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: myapp-postgres
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
    ports:
      - "${DBPORT}:5432"  # Map the external port to the PostgreSQL internal port

  myapp:
    image: golang:latest
    container_name: myapp-container
    working_dir: /go/src/app
    volumes:
      - ./app:/go/src/app  # Mount your Go app directory to the container
    environment:
      DB_USER: ${DBUSER}
      DB_PASS: ${DBPASS}
      DB_HOST: ${DBHOST}
      DB_PORT: ${DBPORT}
      DB_NAME: ${DBNAME}
      JWT_KEY: ${JWTKey}
    depends_on:
      - postgres
    ports:
      - "8080:8080"  # Expose your app's port, adjust if your app runs on a different port
    command: go run main.go  # Modify this if you have a different command to start your Go app
