version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 9100:9100
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
    command: ["php", "-S", "0.0.0.0:9100", "-t", "/var/www/html"]

  api:
    container_name: kentangapi
    image: wushie/tokokentang:v3
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: on-failure

networks:
  default: