FROM golang:1.20-alpine

##create folder APP
RUN mkdir /app

##set main directory
WORKDIR /app

##copy the whole file to app
COPY . .

##create executable
RUN go build -o main .

##CMD is defined in the docker-compose.yml file, so it can be omitted here
